[tools]
helmfile = "0.170.1"
node = "20.19.5"
python = "3.14.2"
kustomize = "5.7.0"
tflint = "0.52.0"
ghq = "1.8.0"
aws-cli = { version = "2.32.13", symlink_bins = "true" }
kubectl = "1.32.0"
gh = "latest"
tfenv = "3.0.0"
go = "1.24"
peco = "0.5.11"
fzf = "0.62"
viddy = "1.3"
neovim = "0.11.2"
yq = "4.9.8"
uv = "0.7.13"
kind = "0.29.0"
yarn = "latest"
delta = "latest"
circleci = "latest"
trivy = "latest"
direnv = "2.37.1"
poetry = "2.2.1"
tmux = "3.6"
pipx = "1.8.0"
aws-vault = "7.2.0"

[settings]
idiomatic_version_file_enable_tools = []
